name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Read .tool-versions
        id: tool-versions
        run: echo "nodejs_version=$(grep nodejs .tool-versions | cut -d' ' -f2)" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.tool-versions.outputs.nodejs_version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm run test:ci
