name: CI
on: [push]

jobs:
  build:
    name: Compile, Lint, Format, and Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'America/New_York'

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Use Node ${{ steps.versions.outputs.nodejs }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: Generate Expo Route Types
        run: npm run expo:types

      - name: Check types
        run: npm run ts:check

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Test
        run: npm run test
